type: deeplabv3
name: deeplabv3_resnet50
display_name: DeepLabV3 ResNet50
model_path: D:/homework/X-anylabeling/my_xanylabeling_project/deeplabv3_resnet50.onnx  # 替换为你的实际路径
input_width: 512
input_height: 512
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
conf_threshold: 0.5
classes:
  - background
  - aeroplane
  - bicycle
  - bird
  - boat
  - bottle
  - bus
  - car
  - cat
  - chair
  - cow
  - diningtable
  - dog
  - horse
  - motorbike
  - person
  - pottedplant
  - sheep
  - sofa
  - train
  - tvmonitor